# -*- coding: utf-8 -*-
"""io.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_kYJjJgF5pwQ64mc_fD3XhP38WBb3HWj
"""

# Importar as bibliotecas necessárias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.utils import resample

# Função para calcular o intervalo de confiança via bootstrapping
def bootstrap_ci(data1, data2, n_bootstraps=1000, ci=95):
    boot_diffs = []
    for _ in range(n_bootstraps):
        sample1 = resample(data1, replace=True)
        sample2 = resample(data2, replace=True)
        boot_diffs.append(np.mean(sample1) - np.mean(sample2))
    lower = np.percentile(boot_diffs, (100 - ci) / 2)
    upper = np.percentile(boot_diffs, 100 - (100 - ci) / 2)
    return lower, upper

# Função para calcular o efeito d de Cohen
def cohen_d(group1, group2):
    diff = np.mean(group1) - np.mean(group2)
    pooled_std = np.sqrt((np.std(group1, ddof=1) ** 2 + np.std(group2, ddof=1) ** 2) / 2)
    return diff / pooled_std

# Definir URL do dataset
url = 'https://docs.google.com/spreadsheets/d/1SN8UqTkmoOFvzxz5fVug21LnCdnPhkNf6homjV7XFL0/export?format=csv&gid=650803662'

# Carregar os dados diretamente da URL
df = pd.read_csv(url)

# Limpar e formatar dados
df = df.replace('-', np.nan)  # Substituir '-' por NaN
df = df.apply(pd.to_numeric, errors='coerce')  # Converter para numérico
df = df.dropna(how='all')  # Remover linhas com todos os valores NaN
df.reset_index(drop=True, inplace=True)  # Resetar os índices

# Dividir em adultos e crianças
df_adult = df[df['isAdult'] == 1]
df_child = df[df['isAdult'] == 0]

# 1. Teste de Levene para homogeneidade de variância na variável N back
levene_stat, levene_p = stats.levene(df_adult['nback'], df_child['nback'], nan_policy='omit')
print(f"1) Teste de Levene para homogeneidade de variância (N back):\nEstatística = {levene_stat:.4f}, p-valor = {levene_p:.4f}")
if levene_p > 0.05:
    print("Resultado: As variâncias são homogêneas.\n")
else:
    print("Resultado: As variâncias não são homogêneas.\n")

# 2. Teste de normalidade (Shapiro-Wilk) e homogeneidade de variância (Levene) na variável "conflict"
shapiro_adult_conflict = stats.shapiro(df_adult['conflict'].dropna())
shapiro_child_conflict = stats.shapiro(df_child['conflict'].dropna())
levene_conflict_stat, levene_conflict_p = stats.levene(df_adult['conflict'], df_child['conflict'], nan_policy='omit')

print(f"2) Teste de Shapiro-Wilk para normalidade (Condição Conflito):")
print(f"Adultos: W = {shapiro_adult_conflict[0]:.4f}, p = {shapiro_adult_conflict[1]:.4f}")
print(f"Crianças: W = {shapiro_child_conflict[0]:.4f}, p = {shapiro_child_conflict[1]:.4f}")
print(f"Teste de Levene para homogeneidade de variância (Conflito): Estatística = {levene_conflict_stat:.4f}, p-valor = {levene_conflict_p:.4f}")

# Avaliando os pressupostos do teste t:
if shapiro_adult_conflict[1] > 0.05 and shapiro_child_conflict[1] > 0.05 and levene_conflict_p > 0.05:
    print("Resultado: A tarefa de rede de atenção (condição conflito) atende aos pressupostos do teste t.\n")
else:
    print("Resultado: A tarefa de rede de atenção (condição conflito) não atende completamente aos pressupostos do teste t.\n")

# 3. Teste t de amostras independentes nas variáveis atComp e wmComp com bootstrapping
t_stat_atComp, p_val_atComp = stats.ttest_ind(df_adult['atComp'], df_child['atComp'], nan_policy='omit')
ci_lower_atComp, ci_upper_atComp = bootstrap_ci(df_adult['atComp'].dropna(), df_child['atComp'].dropna())
print(f"3) Teste t para componente de atenção (atComp):\nEstatística t = {t_stat_atComp:.4f}, p-valor = {p_val_atComp:.4f}")
print(f"Intervalo de confiança via bootstrapping (95%): [{ci_lower_atComp:.4f}, {ci_upper_atComp:.4f}]\n")

t_stat_wmComp, p_val_wmComp = stats.ttest_ind(df_adult['wmComp'], df_child['wmComp'], nan_policy='omit')
ci_lower_wmComp, ci_upper_wmComp = bootstrap_ci(df_adult['wmComp'].dropna(), df_child['wmComp'].dropna())
print(f"Teste t para componente da memória de trabalho (wmComp):\nEstatística t = {t_stat_wmComp:.4f}, p-valor = {p_val_wmComp:.4f}")
print(f"Intervalo de confiança via bootstrapping (95%): [{ci_lower_wmComp:.4f}, {ci_upper_wmComp:.4f}]\n")

# 4. Cálculo do tamanho de efeito (d de Cohen)
cohen_d_atComp = cohen_d(df_adult['atComp'].dropna(), df_child['atComp'].dropna())
print(f"4) Efeito de Cohen para componente de atenção (atComp): d = {cohen_d_atComp:.3f}")

cohen_d_wmComp = cohen_d(df_adult['wmComp'].dropna(), df_child['wmComp'].dropna())
print(f"Efeito de Cohen para componente da memória de trabalho (wmComp): d = {cohen_d_wmComp:.3f}\n")

# 5. Relatório da análise
print("5) Relatório da análise:")
print(f"Para o componente de atenção (atComp), o teste t indicou uma estatística de t = {t_stat_atComp:.4f} com um p-valor de {p_val_atComp:.4f}.")
print(f"O intervalo de confiança de 95% gerado via bootstrapping foi [{ci_lower_atComp:.4f}, {ci_upper_atComp:.4f}].")
print(f"O tamanho de efeito (d de Cohen) foi de {cohen_d_atComp:.3f}, indicando um efeito {'pequeno' if abs(cohen_d_atComp) < 0.5 else 'moderado' if abs(cohen_d_atComp) < 0.8 else 'grande'}.\n")

print(f"Para o componente da memória de trabalho (wmComp), o teste t apresentou uma estatística de t = {t_stat_wmComp:.4f} com um p-valor de {p_val_wmComp:.4f}.")
print(f"O intervalo de confiança de 95% gerado via bootstrapping foi [{ci_lower_wmComp:.4f}, {ci_upper_wmComp:.4f}].")
print(f"O tamanho de efeito (d de Cohen) foi de {cohen_d_wmComp:.3f}, indicando um efeito {'pequeno' if abs(cohen_d_wmComp) < 0.5 else 'moderado' if abs(cohen_d_wmComp) < 0.8 else 'grande'}.\n")

# 6. Comparação entre Raven e PPVT
# Sincronizar os dados de Raven e PPVT, removendo pares incompletos
raven_ppvt_df = df[['raven', 'ppvt']].dropna()

# Teste t pareado para Raven e PPVT
raven_vs_ppvt_t_stat, raven_vs_ppvt_p_val = stats.ttest_rel(raven_ppvt_df['raven'], raven_ppvt_df['ppvt'])
ci_lower_raven_vs_ppvt, ci_upper_raven_vs_ppvt = bootstrap_ci(raven_ppvt_df['raven'], raven_ppvt_df['ppvt'])
cohen_d_raven_vs_ppvt = cohen_d(raven_ppvt_df['raven'], raven_ppvt_df['ppvt'])

print(f"6) Teste t para diferenças entre Raven e PPVT:\nEstatística t = {raven_vs_ppvt_t_stat:.4f}, p-valor = {raven_vs_ppvt_p_val:.4f}")
print(f"Intervalo de confiança via bootstrapping (95%): [{ci_lower_raven_vs_ppvt:.4f}, {ci_upper_raven_vs_ppvt:.4f}]")
print(f"Efeito de Cohen para diferença entre Raven e PPVT: d = {cohen_d_raven_vs_ppvt:.3f}")